### ISSUE TITLE
No data

### ISSUE THREAD

**Issue by incarvr6** [HandyHat/ha-hildebrandglow-dcc#14]
As of 29/08/21 12:00 Home assistant is not getting any data, status unavailable.
Removing and readding integration dose not help.

**Comment by danmed** [comment]
I'm also seeing this.. I've removed and re-added and i'm getting the below in the logs : 

`2021-08-31 10:55:07 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up hildebrandglow_dcc platform for sensor
Traceback (most recent call last):
  File "/config/custom_components/hildebrandglow_dcc/sensor.py", line 33, in async_setup_entry
    resources = await hass.async_add_executor_job(glow.retrieve_resources)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/hildebrandglow_dcc/glow.py", line 78, in retrieve_resources
    raise InvalidAuth
custom_components.hildebrandglow_dcc.glow.InvalidAuth
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/hildebrandglow_dcc/sensor.py", line 36, in async_setup_entry
    await Glow.handle_failed_auth(config, hass)
TypeError: handle_failed_auth() missing 1 required positional argument: 'hass'`

**Comment by danmed** [comment]
Interestingly, mine has just started working again... 

I removed the integration and re-added it and after abotu 5 minutes it seems to be working again.

**Comment by incarvr6** [comment]
Mine has just started working again as well, but it did take about an hour after re adding integration.

**Comment by HandyHat** [comment]
Please see here: https://community.home-assistant.io/t/hildebrandglow-smart-meters-smets2/267603/77

**Comment by ColinRobbins** [comment]
I'm seeing this issue too.   It seems after a while the authentication times out.
Removing and re-installing the integration seems to fix it.

**Comment by googanhiem** [comment]
I've been looking at the code and @ColinRobbins is right, its an issue with `handle_failed_auth`,  it looks like its having an issue getting or updating the config_entries information.

This error will happen to everyone using this weekly, as the token has a 7 days expiry on it.

Waiting a bit, deleting the integration and re-adding it is the current workaround (showing the current auth system isn't at fault, its just the reauth calls that aren't working).

**Comment by ColinRobbins** [comment]
@googanhiem, I think I have implemented a fix.  Testing locally.
If all goes well, I’ll post the change and make a pull request over the weekend.

**Comment by googanhiem** [comment]
Looks good. You could test it by changing the token expiry in the configentries file (it's in .storage). 
I'll try it tonight.

**Comment by googanhiem** [comment]
Unfortunately mine didn't refresh the token correctly after a week. Same error.

**Comment by ColinRobbins** [comment]
Same here, but a slightly different error (getting a 404 error, not a 401).
With a simple restart of hass it re authenticated OK.
I’ve made another modification to handle the 404 error.
See you here same time next week to see if that works!

**Comment by ColinRobbins** [comment]
Looking at the code, I think there is an issue with updating the "glow" instance in the running sensor.
I've tried a fix...
https://github.com/HandyHat/ha-hildebrandglow-dcc/compare/main...ColinRobbins:main
Will see what happens next time fails.
Some the logging will need removing in time.

**Comment by chesterflaps** [comment]
I have had this integration for a few weeks and not once has it given the correct data. Always saying I have used around 0.50kwh per day. I wish!
