### ISSUE TITLE
One error and several warnings on HA startup

### ISSUE THREAD

**Issue by PaulOckenden** [HandyHat/ha-hildebrandglow-dcc#377]
Latest versions of HA and Glow integration.

2023-11-15 16:55:45.215 ERROR (MainThread) [custom_components.hildebrandglow_dcc.sensor] Unexpected exception: 'description'. Please open an issue
Traceback (most recent call last):
  File "/config/custom_components/hildebrandglow_dcc/sensor.py", line 64, in async_setup_entry
    resources = await hass.async_add_executor_job(virtual_entity.get_resources)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/glowmarkt/glowmarkt.py", line 43, in get_resources
    return self.client.get_resources(self.id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/glowmarkt/glowmarkt.py", line 169, in get_resources
    r.description = elt["description"]
                    ~~~^^^^^^^^^^^^^^^
KeyError: 'description'

2023-11-15 16:55:46.993 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.dcc_sourced_smart_electricity_meter_cost_today (<class 'custom_components.hildebrandglow_dcc.sensor.Cost'>) is using state class 'total_increasing' which is impossible considering device class ('monetary') it is using; expected None or one of 'total'; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/HandyHat/ha-hildebrandglow-dcc/issues

2023-11-15 16:55:46.994 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.dcc_sourced_smart_electricity_meter_cost_today_2 (<class 'custom_components.hildebrandglow_dcc.sensor.Cost'>) is using state class 'total_increasing' which is impossible considering device class ('monetary') it is using; expected None or one of 'total'; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/HandyHat/ha-hildebrandglow-dcc/issues

2023-11-15 16:55:46.995 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.dcc_sourced_smart_gas_meter_cost_today (<class 'custom_components.hildebrandglow_dcc.sensor.Cost'>) is using state class 'total_increasing' which is impossible considering device class ('monetary') it is using; expected None or one of 'total'; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/HandyHat/ha-hildebrandglow-dcc/issues

**Comment by incarvr6** [comment]
Similar here`Logger: homeassistant.components.sensor
Source: components/sensor/__init__.py:528
Integration: Sensor (documentation, issues)
First occurred: 09:19:49 (2 occurrences)
Last logged: 09:19:49

Entity sensor.dcc_sourced_smart_gas_meter_cost_today (<class 'custom_components.hildebrandglow_dcc.sensor.Cost'>) is using state class 'total_increasing' which is impossible considering device class ('monetary') it is using; expected None or one of 'total'; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/HandyHat/ha-hildebrandglow-dcc/issues
Entity sensor.dcc_sourced_smart_electricity_meter_cost_today (<class 'custom_components.hildebrandglow_dcc.sensor.Cost'>) is using state class 'total_increasing' which is impossible considering device class ('monetary') it is using; expected None or one of 'total'; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/HandyHat/ha-hildebrandglow-dcc/issues`
