### ISSUE TITLE
Unexpected exception: list index out of range. (from logs)

### ISSUE THREAD

**Issue by chronvas** [HandyHat/ha-hildebrandglow-dcc#400]
**Describe the bug**
I just seen this log in the settings/logs suggesting to open an issue. Not sure how it affects the functionality of the integration. 

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to 'settings/system'
2. Click on 'logs'
3. Scroll down to 'the error'

**Expected behaviour**
Not sure

**Screenshots**
See logs further down

**Version**
1.0.3 (latest)

**Debug log**
Enable debug logging by following the instructions [here](https://github.com/HandyHat/ha-hildebrandglow-dcc#debugging)

```
Logger: custom_components.hildebrandglow_dcc.sensor
Source: custom_components/hildebrandglow_dcc/sensor.py:186
integration: Hildebrand Glow (DCC) ([documentation](https://github.com/HandyHat/ha-hildebrandglow-dcc), [issues](https://github.com/HandyHat/ha-hildebrandglow-dcc/issues))
First occurred: 1:05:10 AM (34 occurrences)
Last logged: 5:05:10 AM
Unexpected exception: list index out of range. Please open an issue

Traceback (most recent call last):
  File "/config/custom_components/hildebrandglow_dcc/sensor.py", line 186, in daily_data
    v = readings[0][1].value
        ~~~~~~~~^^^
IndexError: list index out of range
```

**Additional context**

**Comment by nickmit-1957** [comment]
I am getting the same error
2024-08-16 03:30:08.318 ERROR (MainThread) [custom_components.hildebrandglow_dcc.sensor] Unexpected exception: list index out of range. Please open an issue
Traceback (most recent call last):
  File "/config/custom_components/hildebrandglow_dcc/sensor.py", line 183, in daily_data
    return readings[0][1].value
           ~~~~~~~~^^^
IndexError: list index out of range

**Comment by MichaelMKKelly** [comment]
also seeing this:

Logger: custom_components.hildebrandglow_dcc.sensor
Source: custom_components/hildebrandglow_dcc/sensor.py:183
integration: Hildebrand Glow (DCC) ([documentation](https://github.com/HandyHat/ha-hildebrandglow-dcc), [issues](https://github.com/HandyHat/ha-hildebrandglow-dcc/issues))
First occurred: 01:09:04 (31 occurrences)
Last logged: 03:39:04

Unexpected exception: list index out of range. Please open an issue
Traceback (most recent call last):
  File "/config/custom_components/hildebrandglow_dcc/sensor.py", line 183, in daily_data
    return readings[0][1].value
           ~~~~~~~~^^^
IndexError: list index out of range

**Comment by L81ker** [comment]
same Traceback (most recent call last):
  File "/config/custom_components/hildebrandglow_dcc/sensor.py", line 183, in daily_data
    return readings[0][1].value
           ~~~~~~~~^^^
IndexError: list index out of range

**Comment by L81ker** [comment]
I'm editing the sensor.py file. 

try:
    readings = await hass.async_add_executor_job(
        resource.get_readings, t_from, t_to, "P1D", "sum", True
    )
    _LOGGER.debug("Successfully got daily usage for resource id %s", resource.id)
    if readings and len(readings) > 0 and len(readings[0]) > 1:
        return readings[0][1].value
    else:
        _LOGGER.warning("No readings available or unexpected data format")
except requests.Timeout as ex:
    _LOGGER.error("Timeout: %s", ex)
except requests.exceptions.ConnectionError as ex:
    _LOGGER.error("Cannot connect: %s", ex)
# Can't use the RuntimeError exception from the library as it's not a subclass of Exception
except Exception as ex:  # pylint: disable=broad-except
    if "Request failed" in str(ex):
        _LOGGER.warning(
            "Non-200 Status Code. The Glow API may be experiencing issues"
        )
    else:
        _LOGGER.exception("Unexpected exception: %s. Please open an issue", ex)
return None

This code adds a check to ensure readings is not empty and has the expected structure before accessing its elements. This should prevent the IndexError from occurring.  Trying it now. Could be a work around

**Comment by bucklevision** [comment]
Also here...
Unexpected exception: list index out of range. Please open an issue
Traceback (most recent call last):
  File "/config/custom_components/hildebrandglow_dcc/sensor.py", line 196, in daily_data
    v = readings[0][1].value
        ~~~~~~~~^^^
IndexError: list index out of range

**Comment by MankeyJohn** [comment]
This error originated from a custom integration.

Logger: custom_components.hildebrandglow_dcc.sensor
Source: custom_components/hildebrandglow_dcc/sensor.py:183
integration: Hildebrand Glow (DCC) (documentation, issues)
First occurred: 01:06:43 (6 occurrences)
Last logged: 01:31:43

Unexpected exception: list index out of range. Please open an issue
Traceback (most recent call last):
  File "/config/custom_components/hildebrandglow_dcc/sensor.py", line 183, in daily_data
    return readings[0][1].value
           ~~~~~~~~^^^
IndexError: list index out of range

**Comment by DRCombes** [comment]
I'm getting the same error on two new installations of this integration (for two different GlowMarkt accounts).

Unsure if this error is the reason that I'm not seeing the same data being pulled through to HA as I'm seeing in the Bright App.

**Comment by andrey-zotov** [comment]
The solution is here, fixed it for me:
https://github.com/HandyHat/ha-hildebrandglow-dcc/issues/396#issuecomment-2038364754
Hope the mainainer can merge it.
