### ISSUE TITLE
v0.5.1 authentication error

### ISSUE THREAD

**Issue by si458** [HandyHat/ha-hildebrandglow-dcc#69]
**Describe the bug**
```
2021-11-08 10:32:03 DEBUG (SyncWorker_7) [custom_components.hildebrandglow_dcc.glow] Post 1: (https://api.glowmarkt.com/api/v0-1/auth)
2021-11-08 10:32:03 ERROR (MainThread) [custom_components.hildebrandglow_dcc.config_flow] Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/hildebrandglow_dcc/config_flow.py", line 60, in async_step_user
    info = await validate_input(self.hass, user_input)
  File "/config/custom_components/hildebrandglow_dcc/config_flow.py", line 37, in validate_input
    glow = await hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/hildebrandglow_dcc/glow.py", line 46, in authenticate
    response = requests.http.post(url, json=auth, headers=headers)
AttributeError: module 'requests' has no attribute 'http'
```

**To Reproduce**
1. add latest version `v0.5.1`
2. try setting up the integration

**Expected behaviour**
to authorise no problem

**Screenshots**

**Version**
Home Assistant 2021.11.1 - add on v0.5.1 

**Debug log**
Enable debug logging by following the instructions [here](https://github.com/HandyHat/ha-hildebrandglow-dcc#debugging)

**Additional context**

**Comment by si458** [comment]
@ColinRobbins i think the http request might me faulty?

**Comment by si458** [comment]
returing `requests.http.post` to `requests.post` fixes the issue

**Comment by ColinRobbins** [comment]
Sorry about that, look like I messed up a recent pull request, as this is OK in my dev tree.
Just issued a PR to resolve it.
